In [103]:
#pip install wget

In [104]:
#!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

In [105]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [106]:
pd.__version__

'2.2.1'

In [107]:
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'

In [108]:
df = pd.read_csv(url)

In [109]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [110]:
df.to_csv('laptops.csv')

In [111]:
len(df)

2160

In [112]:
df.shape

(2160, 12)

In [113]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [114]:
brands = df['Brand'].nunique()

In [115]:
brands

27

In [116]:
df.isnull()

Laptop  Status  Brand  Model    CPU    RAM  Storage  Storage type  \
0      False   False  False  False  False  False    False         False   
1      False   False  False  False  False  False    False         False   
2      False   False  False  False  False  False    False         False   
3      False   False  False  False  False  False    False         False   
4      False   False  False  False  False  False    False         False   
...      ...     ...    ...    ...    ...    ...      ...           ...   
2155   False   False  False  False  False  False    False         False   
2156   False   False  False  False  False  False    False         False   
2157   False   False  False  False  False  False    False         False   
2158   False   False  False  False  False  False    False         False   
2159   False   False  False  False  False  False    False         False   

        GPU  Screen  Touch  Final Price  
0      True   False  False        False  
1      True   False  False        False  
2      True   False  False        False  
3     False   False  False        False  
4      True   False  False        False  
...     ...     ...    ...          ...  
2155  False   False  False        False  
2156  False   False  False        False  
2157  False   False  False        False  
2158   True   False  False        False  
2159   True   False  False        False  

[2160 rows x 12 columns]

In [117]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [118]:
missingColumns = df.isnull().sum().gt(0).sum()
missingColumns

3

In [119]:
df['Final Price'].max()

7150.47

In [120]:
dellPrice = np.max(df[pd.Series(df['Brand'] == 'Dell')]['Final Price'])
dellPrice

3936.0

In [121]:
#Q6. Median value of Screen

In [122]:
#1.Find the median value of Screen column in the dataset.

In [123]:
median= df['Screen'].median()
median

15.6

In [124]:
#2.Next, calculate the most frequent value of the same Screen column.

In [125]:
mostFrequentScreen= df['Screen'].mode()[0]
mostFrequentScreen 

15.6

In [126]:
#3.Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [127]:
df['Screen'].fillna(mostFrequentScreen)
medianAfter = df['Screen'].median()
medianAfter

15.6

In [128]:
#Has it changed?

In [129]:
changed = median != medianAfter
changed

False

In [130]:
#Q7. Sum of weights

In [131]:
innjoo = df[df['Brand'] == 'Innjoo']
innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [132]:
filtered = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]
filtered

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [133]:
X = filtered.to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [134]:
XTX = np.dot(X.T, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [135]:
invertXTX = np.linalg.inv(XTX)
invertXTX

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [136]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [137]:
w = np.dot(np.dot(invertXTX, X.T), y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [138]:
sum = np.sum(w)
sum

91.29988062995815